clear X;

clear A;
incr A;
incr A;
incr A;
incr A;
while A not 0 do;
    clear B;
    incr B;
    incr B;
    incr B;
    incr B;
    while B not 0 do;
        clear C;
        incr C;
        incr C;
        incr C;
        incr C;
        while C not 0 do;
            clear D;
            incr D;
            incr D;
            incr D;
            incr D;
            while D not 0 do;
                clear E;
                incr E;
                incr E;
                incr E;
                incr E;
                while E not 0 do;
                    clear F;
                    incr F;
                    incr F;
                    incr F;
                    incr F;
                    while F not 0 do;
                        incr X;
                        decr F;
                    end;
                    decr E;
                end;
                decr D;
            end;
            decr C;
        end;
        decr B;
    end;
    decr A;
end;
#vars:A=0,B=0,C=0,D=0,E=0,F=0,X=4096